version: "2"

services:
  jenkins:
    build: ./jenkins
    image: jenkinsdev
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
  sonarqube:
    image: sonarqube:6.1
    ports:
      - "9000:9000"
    networks:
      - sonar
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
  db:
    image: postgres:9.6.1
    networks:
      - sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

networks:
  sonar:
    driver: bridge

volumes:
  jenkins_home: