version: "2"

services:
  sonarqube:
    image: sonarqube:6.1
    ports:
      - "9000:9000"
    networks:
      - sonar
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
  db:
    image: postgres:9.6.1
    networks:
      - sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

networks:
  sonar:
    driver: bridge
