---

- file: name=/mnt/shared_volume/registry mode=644 state=directory

- include: ../../docker-service/tasks/main.yml
  vars:
    name: registry
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
     - type=bind,src=/mnt/shared_volume/registry,dst=/var/lib/registry

- wait_for:
    host: 127.0.0.1
    port: 5000 
    timeout: 45 
    state: started

- docker_login:
    registry: 127.0.0.1:5000
    username: test
    password: test
    email: test@example.com
