- name: Prerequisites packages are installed
  apt: name={{ item }} state=installed
  with_items:
    - apt-transport-https 
    - ca-certificates
    - python-setuptools # for easy_install

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo debian-{{ debian_version }} main
    update_cache: yes
    state: present

- name: Docker is present
  apt:
    name: docker-engine
    state: latest
    force: yes

- name: pip is up to date
  easy_install:
    name: pip 
    state: present

- name: docker-py is present
  pip:
    name: docker-py
    state: present

- name: Docker service files are present
  template:
    src: "{{ docker_service }}"
    dest: "{{ docker_service_dest }}"
    force: yes
  register: copy_result

- name: Daemon is reloaded
  command: systemctl daemon-reload
  when: copy_result|changed

- name: Docker group is added to users
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: 
    - "{{ users }}"
  register: user_groups


- name: Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed or user_groups|changed

- name: Docker service is started
  service:
    name: docker
    state: started
